name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  PLUGIN_NAME: file-ignore

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          
          # 检查版本号是否匹配
          manifest_version=$(cat manifest.json | jq -r '.version')
          
          if [ "$tag" != "$manifest_version" ]; then
            echo "Error: Tag version ($tag) does not match manifest.json version ($manifest_version)"
            exit 1
          fi
          
          # 创建发布包
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css versions.json ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          
          gh release create "$tag" \
            --draft \
            --title="$tag" \
            --notes "Release $tag" \
            main.js manifest.json styles.css versions.json "${{ env.PLUGIN_NAME }}.zip" 