name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  PLUGIN_NAME: file-ignore

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Current ref: $GITHUB_REF"
          tag="${GITHUB_REF#refs/tags/}"
          echo "Extracted tag: $tag"
          
          # 检查版本号是否匹配
          manifest_version=$(cat manifest.json | jq -r '.version')
          echo "Manifest version: $manifest_version"
          
          if [ "$tag" != "$manifest_version" ]; then
            echo "Error: Tag version ($tag) does not match manifest.json version ($manifest_version)"
            exit 1
          fi
          
          # 检查文件是否存在
          for file in main.js manifest.json styles.css versions.json; do
            if [ ! -f "$file" ]; then
              echo "Error: Required file $file does not exist"
              exit 1
            fi
          done
          
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json styles.css versions.json 